name: prueba_emociones
dependencies:
  - python=3.10
  - pip
  - pip:
      - datasets
      - pandas
      - numpy
      - scikit-learn
      - jellyfish
      - matplotlib
      - seaborn
      - black>=24.0.0
      - ruff>=0.5.0
      - pytest>=8.0.0
